/**
 * Read-only bash ruleset. Shared by:
 * 1. The plan agent, which restricts shell commands to this set.
 * 2. The todo gate, which lets the model use read-only shell commands
 *    without a plan but blocks side-effect commands until an in_progress
 *    todo with notes is in place.
 *
 * The ruleset is defined as a Permission config subtree (Record<pattern,
 * "allow" | "deny" | "ask">). Evaluating a command pattern against this
 * subtree returns "allow" for read-only commands and "deny" for everything
 * else — same semantics the permission system uses for plan mode.
 */
export const READ_ONLY_BASH: Record<string, "allow" | "deny" | "ask"> = {
  "*": "deny",
  "grep *": "allow",
  "rg *": "allow",
  "find *": "allow",
  "cat *": "allow",
  "ls *": "allow",
  "head *": "allow",
  "tail *": "allow",
  "wc *": "allow",
  "sort *": "allow",
  "uniq *": "allow",
  "diff *": "allow",
  "file *": "allow",
  "stat *": "allow",
  "du *": "allow",
  "tree *": "allow",
  "pwd *": "allow",
  "which *": "allow",
  "printenv *": "allow",
  "jq *": "allow",
  "cut *": "allow",
  "tr *": "allow",
  // Binary / structured inspection — safe, and terminal-bench uses them often.
  "xxd *": "allow",
  "od *": "allow",
  "hexdump *": "allow",
  "readelf *": "allow",
  "objdump *": "allow",
  "nm *": "allow",
  "strings *": "allow",
  "size *": "allow",
  "ldd *": "allow",
  "otool *": "allow",
  "dwarfdump *": "allow",
  // Shell introspection
  "echo *": "allow",
  "printf *": "allow",
  "date *": "allow",
  "uname *": "allow",
  "hostname *": "allow",
  "whoami *": "allow",
  "id *": "allow",
  "env *": "allow",
  "type *": "allow",
  "command *": "allow",
  "basename *": "allow",
  "dirname *": "allow",
  "readlink *": "allow",
  "realpath *": "allow",
  "ps *": "allow",
  "cmp *": "allow",
  "base64 *": "allow",
  "md5sum *": "allow",
  "sha1sum *": "allow",
  "sha256sum *": "allow",
  "column *": "allow",
  "paste *": "allow",
  "fold *": "allow",
  "nl *": "allow",
  "tac *": "allow",
  "rev *": "allow",
  "yq *": "allow",
  "awk *": "allow",
  // shell no-ops used in chains like "foo || true"
  "true *": "allow",
  "false *": "allow",
  // waits and small utilities commonly used inside read-only probes
  "sleep *": "allow",
  "timeout *": "deny", // timeout wraps another command — don't whitelist; re-evaluate the wrapped command instead
  "test *": "allow",
  "[ *": "allow",
  "xargs *": "deny", // xargs runs another command — don't whitelist
  "seq *": "allow",
  "yes *": "deny", // infinite output, avoid
  "cksum *": "allow",
  "stdbuf *": "deny", // wraps another command

  // git: allow all, then deny destructive subcommands
  "git *": "allow",
  "git -c *": "deny",
  "git add *": "deny",
  "git am *": "deny",
  "git apply *": "deny",
  "git bisect *": "deny",
  "git checkout *": "deny",
  "git cherry-pick *": "deny",
  "git clean *": "deny",
  "git clone *": "deny",
  "git commit *": "deny",
  "git config *": "deny",
  "git filter-branch *": "deny",
  "git gc *": "deny",
  "git init *": "deny",
  "git maintenance *": "deny",
  "git merge *": "deny",
  "git mv *": "deny",
  "git notes add *": "deny",
  "git notes append *": "deny",
  "git notes edit *": "deny",
  "git notes merge *": "deny",
  "git notes remove *": "deny",
  "git notes prune *": "deny",
  "git pack-refs *": "deny",
  "git prune *": "deny",
  "git pull *": "deny",
  "git push *": "deny",
  "git rebase *": "deny",
  "git reflog expire *": "deny",
  "git reflog delete *": "deny",
  "git repack *": "deny",
  "git replace *": "deny",
  "git reset *": "deny",
  "git restore *": "deny",
  "git revert *": "deny",
  "git rm *": "deny",
  "git sparse-checkout *": "deny",
  "git stash *": "deny",
  "git submodule update *": "deny",
  "git submodule init *": "deny",
  "git submodule add *": "deny",
  "git submodule deinit *": "deny",
  "git switch *": "deny",
  "git tag *": "deny",
  "git update-index *": "deny",
  "git update-ref *": "deny",
  "git worktree *": "deny",
  // re-allow safe read-only subcommands
  "git stash list *": "allow",
  "git stash show *": "allow",
  "git tag -l *": "allow",
  "git tag --list *": "allow",
  "git reflog show *": "allow",
  "git reflog list *": "allow",
  "git notes list *": "allow",
  "git submodule status *": "allow",
  "git submodule summary *": "allow",
  "git worktree list *": "allow",
  "git config --list *": "allow",
  "git config -l *": "allow",
  "git config --get *": "allow",
  "git config --get-all *": "allow",
  "git config --get-regexp *": "allow",
  // deny dangerous find flags
  "find * -exec *": "deny",
  "find * -execdir *": "deny",
  "find * -delete *": "deny",
  "find * -ok *": "deny",
  "find * -okdir *": "deny",
  // deny sort file writing
  "sort -o *": "deny",
  "sort --output *": "deny",
  // deny output redirections
  "* > *": "deny",
  "* >> *": "deny",
}
